### ISSUE TITLE
[BUG] chat broken by colouredchat mod

### ISSUE THREAD

**Issue by DrToxic** [ErdbeerbaerLP/DiscordIntegration-Forge#156]
**What happened?**
Sending messages from Minecraft to Discord; Messages never showed up.

**What should happen?**
Chat Message should be sent from Minecraft to Discord.

**Steps to reproduce**
1: Install colouredchat-1.12.2-0.3.0-beta.jar Mod
[https://www.curseforge.com/minecraft/mc-mods/colouredchat]

2: Send messages in game

3: Lack messages in Discord Channel

**Version**
- [X] 1.12
- [ ] 1.14
- [ ] 1.15

**Mod Version**
dcintegration-1.1.18-1.12.jar

**Additional info**
None, really... It's just something I noticed. I don't have any useful log as of yet.

**Comment by ErdbeerbaerLP** [comment]
Is this still relevant for 1.16+? If yes simply re-open and I try to add compatibility
