### ISSUE TITLE
[Suggestion] Forward warnings to discord

### ISSUE THREAD

**Issue by goethenorris** [ErdbeerbaerLP/DiscordIntegration-Forge#188]
**Platform**
- MineOS on Freenas 11.4u4 (FreeBSD)
- [x] Forge
- [ ] Spigot

**What you want to be added?**
- Froward "[Server thread/WARN]" messages to discord same as chat

for players who like to spam hundreds of chicken this can be a useful warning system

**Comment by ErdbeerbaerLP** [comment]
This can be done using an seperate mod if required. Won't implement it as it would be pretty much spamming with many mods installed
