### ISSUE TITLE
[BUG] Some Webhook profile pictures render as Steve

### ISSUE THREAD

**Issue by Silverarmor** [ErdbeerbaerLP/DiscordIntegration-Forge#196]
**What happened?**
- Some webhook profile pictures do not render (they are steve)

**What should happen?**
- Head pictures from each player

**Steps to reproduce**
- Unknown - occured on startup & after restarts.

**Version**
-
- [x] 1.12
- [ ] 1.16

**Platform**
-
- [x] Forge
- [ ] Spigot

Mod version:  

**Config file**
-https://pastebin.com/raw/mGT5Ewd3

**Additional info**
-
![image](https://user-images.githubusercontent.com/23619946/106072377-efa71980-616c-11eb-9eff-e84f80971360.png)
![image](https://user-images.githubusercontent.com/23619946/106072402-fe8dcc00-616c-11eb-9e22-0765c143e311.png)

**Comment by Silverarmor** [comment]
Troubleshooted:
People who use the "alex" skin base have this error only.
![image](https://user-images.githubusercontent.com/23619946/106323422-4848f480-62dc-11eb-8d9c-82e061782978.png)

**Comment by ErdbeerbaerLP** [comment]
This might get fixed with the likely coming backport from 1.16 after another big change of how the mod is structured and built

**Comment by Silverarmor** [comment]
Has this been resolved? ty

**Comment by ErdbeerbaerLP** [comment]
It should be 😉 , if not, feel free to re-open
