### ISSUE TITLE
[BUG] Question/possible bug?

### ISSUE THREAD

**Issue by YOYOK9** [ErdbeerbaerLP/DiscordIntegration-Forge#197]
**What happened?**
- Basically my console is getting spammed with: 
"[org.slf4j.impl.SimpleLogger:write:318]: [JDA Gateway-Worker 1]: WARN net.dv8tion.jda.internal.requests.WebSocketClient - Hit the WebSocket RateLimit! This can be caused by too many presence or voice status updates (connect/disconnect/mute/deaf). Regular: 1 Voice: 0 Chunking: 0"

Note the number for "Regular" started around 9000ish and has been decreasing over time. Once it hit 1 it has seemed to stop or at least slowed its rate 
**What should happen?**
- Not spam? 

**Steps to reproduce**
- Boot server with latest version
- let run for some time

**Version**
- 
- [ ] 1.12
- [X] 1.16

**Platform**
-
- [X] Forge
- [ ] Spigot

Mod version: dcintegration-2.1.0-1.16

**Config file**
- https://pastebin.com/QnGpDxXf
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://hastebin.com)**
- No crash, log file is a little messy as it split into multiple files (servers been up for a day)
latest log: https://gist.github.com/YOYOK9/244538ad10b26fa176ebca631a33d683

Apologizes Hastebin refused to let me save the log..

**Additional info**
-This is more of a question towards if I should be worried about an output (spam) in mu servers console. Not 100% sure if its a bug

**Comment by ErdbeerbaerLP** [comment]
Did you enable Server Members Intent on your Bot's settings page?
![image](https://user-images.githubusercontent.com/27149563/113401106-28e54b00-93a3-11eb-8575-caf4f8f6c88e.png)

**Comment by YOYOK9** [comment]
Will give it a try, however have a newer issue now, but I think it is just a forge compatibility issue. Will try it in the next update though

**Comment by srnyx** [comment]
Getting something similar and I have both intents on:
https://paste.srnyx.xyz/raw/uyodanefad
