### ISSUE TITLE
[BUG]  NOSIGNATURE | ERROR

### ISSUE THREAD

**Issue by Nito14** [ErdbeerbaerLP/DiscordIntegration-Forge#203]
**What happened?**
- The server crashes

**What should happen?**
- The server should initialize

**Steps to reproduce**
- 
- 

**Version**
-
- [ ] 1.12
- [*] 1.16

**Platform**
-
- [*] Forge
- [ ] Spigot

Mod version: 

**Config file**
-
[Discord-Integration.pdf](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/5914693/Discord-Integration.pdf)

Change the pdf extension to toml

*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://hastebin.com)**
- 
[Crash report.txt](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/5914688/Crash.report.txt)

**Additional info**
- I've noted that the server crashes before the console says NOSGINATURE | ERROR

**Comment by ErdbeerbaerLP** [comment]
try setting `botChannel = 804815822593458211` to `botChannel = "804815822593458211"` and `adminRoleIDs = [  806266765750829138  ]` to `adminRoleIDs = [  "806266765750829138"  ]`
