### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by imthegm** [ErdbeerbaerLP/DiscordIntegration-Forge#210]
**What happened?**
- DiscordIntegration does not appear to register messages coming from bots and there does not appear to be a config option to change that.

**What should happen?**
- DiscordIntegration should either recognize messages from bots by default, or have a config option to change it

**Steps to reproduce**
-  Use in Discord server with Discord-Fabric Link on one server, and DiscordIntegration on another. Both can send to Discord, and D-F Link is able to copy messages from both players and DiscordIntegration in the appropriate channel into the Fabric server, but DiscordIntegration only recognizes messages sent by players in the Discord chat.

**Version**
-
- [ ] 1.12
- [X ] 1.16

**Platform**
-
- [ X] Forge
- [ ] Spigot

Mod version: 
dcintegration-2.1.0-1.16

**Config file**
- https://pastebin.com/vRQkHKuD
*REMOVED BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://hastebin.com)**
- Does not cause crash

**Additional info**
- I can inv to my server for testing if that helps, I have a Valhelsia 3 and an All of Fabric 3 server linked to the same Discord channel and trying to get cross talk to work for users in any of the 3 platforms. Currently the only thing that doesn't work is messages from the Fabric server are not being picked up by DiscordIntegration.

**Comment by ErdbeerbaerLP** [comment]
It actually shouldn't block bot messages at all. It only blocks webhook messages and messages from itself. 

https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/blob/b39345b88e855bc82c660376ac7e900050acbb1c/src/main/java/de/erdbeerbaerlp/dcintegration/common/DiscordEventListener.java#L80
