### ISSUE TITLE
[Bug] Embedding items doesn't seem to work.

### ISSUE THREAD

**Issue by CherenTheCat** [ErdbeerbaerLP/DiscordIntegration-Forge#211]
Hi, I'm using the mod, and the server has Quark, which allows items to be embedded to the chat by hitting Shift+T, giving the same effect as when someone is killed with a named item, and I have the embedding feature enabled, but they post as plain text, just the item name. I'm using the latest 1.16 version, is there any way to get them to show up as embeds?

**Comment by ErdbeerbaerLP** [comment]
I will try to re-implement that feature in for the next update
