### ISSUE TITLE
[Suggestion] Enable/Disable Messagetypes in the config

### ISSUE THREAD

**Issue by BentiGorlich** [ErdbeerbaerLP/DiscordIntegration-Forge#218]
**Platform**
-
- [x] Forge
- [ ] Spigot

**What you want to be added?**
I would like a config option to enable/disable types of messages (death, advancement, player join/leave, server messages).  
I tried just leaving the messages blank, or leaving the channel ID for that message type blank (not for every message type possibile), but that just crashed the mod and therefore the server (maybe bug?)

**Comment by ErdbeerbaerLP** [comment]
Leaving messages empty should work now
