### ISSUE TITLE
Server loading forever [BUG] 

### ISSUE THREAD

**Issue by SupremeMarshal** [ErdbeerbaerLP/DiscordIntegration-Forge#219]
**What happened?**
-The server take a huge amount of time whenever it start or stopping.

**What should happen?**
-Server take 10 times less to load.

**Steps to reproduce**
- Load and unload server with the mod and without the mod
- 

**Version**
- 1.12.2

**Platform**
- [ ] Forge

Mod version: 
last version

**Config file**
-
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://hastebin.com)**
-

**Additional info**
this is what is shown on the console. 
-[22.02 20:57:45] [Server] [Server thread/INFO] [STDOUT]: [derfl007.roads.Roads:init:52]: Init
[22.02 20:57:45] [Server] [OkHttp https://discordapp.com/.../INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:277]: [OkHttp https://discordapp.com/...] WARN RateLimiter - Encountered 429 on route /channels/531093579402051584

It repeat the last message about a thousand time making the server load forever.

**Comment by ErdbeerbaerLP** [comment]
Disable channel description feature
