### ISSUE TITLE
[BUG] Discord image attachments aren't linked in-game

### ISSUE THREAD

**Issue by Science-Bird** [ErdbeerbaerLP/DiscordIntegration-Forge#228]
**What happened?**
- Discord image attachments do not display:

![2021-03-05_12 34 37](https://user-images.githubusercontent.com/80128986/110172420-f64f2f00-7db1-11eb-9343-502f380f7ef3.png)

**What should happen?**
- Before version 2.0.0, attachments do display, as seen here:

![2021-03-05_12 19 18](https://user-images.githubusercontent.com/80128986/110172485-14b52a80-7db2-11eb-8365-becfd4bcb688.png)

**Steps to reproduce**
- Simply send an embedded image in the integrated channel

**Version**
-
- [ ] 1.12
- [ ] 1.15
- [x] 1.16

**Platform**
-
- [x] Forge
- [ ] Spigot

Mod version: 2.1.0 (Seems to affect only versions after 2.0.0 from my testing)

**Config file**
(Used default config file)

**Crash report if available (use https://hastebin.com)**
-

**Additional info**
-

**Comment by ErdbeerbaerLP** [comment]
This is already known and an issue of an external library. Keeping this open until it gets fixed there
