### ISSUE TITLE
[REQUEST] /IP command to display server IP

### ISSUE THREAD

**Issue by goethenorris** [ErdbeerbaerLP/DiscordIntegration-Forge#234]
my server public IP s not static, with no option to request static IP from ISP. 
Could there be an option to add the /IP command to fetch public IP then send it to the discord channel. 

I am aware of the risks of sharing the public IP, but it is managed since it gets sent in a closed discord with only close friends

**Comment by Ki-Tan2934** [comment]
use freedns or buy a domain

**Comment by Ki-Tan2934** [comment]
A feature like this should not be added

**Comment by ErdbeerbaerLP** [comment]
It would also be hard to implement. If you really need it, you can make an DCI addon tho

**Comment by goethenorris** [comment]
I don't know code. I can read instructions and faqs to figure stuff out but other than basic commands I'm lost. 

I own a domain, but it has to be linked everytime the router changes IP, which is too often for my taste. Why spend 5 minutes doing something if it only takes a few hours to automate amirite

**Comment by Ki-Tan2934** [comment]
kinda the whole reason for a domain, don't annoy your players with constant changing IP, you'll have no player base left.
