### ISSUE TITLE
[BUG] Players can no longer join the server after setting up the mod

### ISSUE THREAD

**Issue by markojerry** [ErdbeerbaerLP/DiscordIntegration-Forge#247]
**What happened?**
- I set up the plugin, it initialized correctly according to the console and the webhook, but players can no longer join to the server because it gives the following disconnect output in the client
`Internal Exception: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 1)
`

**What should happen?**
- You should be able to connect normally to the server.

**Steps to reproduce**
- Run 2.1.1 of the mod on a 1.16.4 (35.1.37) Forge Server running the mods viewable on this screenshot: https://prnt.sc/1149wum

**Version**
-
- [ ❌ ] 1.12
- [ ✅ ] 1.16

**Platform**
-
- [ ✅ ] Forge
- [ ❌ ] Spigot

Mod version: 
2.1.1
**Config file**
- https://pastebin.com/raw/vDuGzPQk
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://hastebin.com)**
- No Crash report available

**Additional info**
- None

**Comment by ErdbeerbaerLP** [comment]
Still happening with newest version? If yes just re-open this
