### ISSUE TITLE
Make a discord server for support 

### ISSUE THREAD

**Issue by CandyPillager** [ErdbeerbaerLP/DiscordIntegration-Forge#251]
Please make a discord server where people can get support and also make a better guide (especially on how to add commands). This would really help out. (My Discord is RedstoneRubenNL#5758)

**Comment by ErdbeerbaerLP** [comment]
I might do that server as soon as I get time and space (I am at 100 servers limit).

Improvinb guides is still on my to-do list

**Comment by PABessero** [comment]
@ErdbeerbaerLP you probably could close this issue by now :P
