### ISSUE TITLE
[Suggestion] Whitelist Suggestion

### ISSUE THREAD

**Issue by Tactryl3** [ErdbeerbaerLP/DiscordIntegration-Forge#252]
**Platform**
-
- [X] Forge
- [ ] Spigot

**What you want to be added?**
- Could the mod have the whitelist option just give the player a code when they get sent to the not whitelisted screen. It would be similar to when a player executes /discord link, but would instead just give them the link on the screen and tell them to DM the bot in the discord server?

**Comment by ErdbeerbaerLP** [comment]
Closing this as it is already implemented and I forgot to close it
