### ISSUE TITLE
[BUG] Title May Not Be Empty

### ISSUE THREAD

**Issue by Epic428** [ErdbeerbaerLP/DiscordIntegration-Forge#254]
**What happened?**
- had a crash on our community server - no clue how or why it happened. 

**What should happen?**
- not crash

**Steps to reproduce**
- I wouldn't know bc it happened on the community server
- 

**Version**
-
- [ ] 1.12
- [X] 1.16

**Platform**
-
- [X] Forge
- [ ] Spigot

Mod version: dcintegration-forge-2.1.1-1.16.jar

**Config file**
- https://pastebin.com/QR3ALE4L
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://hastebin.com)**
- https://pastebin.com/MmXSJF00

**Additional info**
- bottom of log

**Comment by Jan-aka-q0** [comment]
It has something to do with the boss name, when I disabled the death message (or rather replaced it with plain text) being sent through it didn't crash.

**Comment by ErdbeerbaerLP** [comment]
Still happening (with latest version)?
