### ISSUE TITLE
[Suggestion][Question]

### ISSUE THREAD

**Issue by poopkickercmyk** [ErdbeerbaerLP/DiscordIntegration-Forge#260]
**Platform**
-
- [x] Forge

**What you want to be added?**
-is ther a way to display admin commands, and if not can there be

**Comment by ErdbeerbaerLP** [comment]
You mean, admin commands like an help command in discord? For that just use the help command with admin role, it should show them.

Or do you mean an channel logging use of admin commands. Use the command log feature, even tho it logs all commands it it also logs use of admin commands

**Comment by poopkickercmyk** [comment]
I mean, i would like to have the command feedback of for example /give in the discord chat so it would get spottet when i cheat

**Comment by poopkickercmyk** [comment]
also, i dont see any command log feature in the config file

**Comment by ErdbeerbaerLP** [comment]
You have to set the channel ID of  command log.channelID in your config

(Variable in code: 
https://github.com/ErdbeerbaerLP/DiscordIntegration-Core/blob/f8762f79a70b95c33032fce419e0e386edf3dd40/src/main/java/de/erdbeerbaerlp/dcintegration/common/storage/Configuration.java#L508 )

**Comment by poopkickercmyk** [comment]
> You have to set the channel ID of command log.channelID in your config
> 
> (Variable in code:
> https://github.com/ErdbeerbaerLP/DiscordIntegration-Core/blob/f8762f79a70b95c33032fce419e0e386edf3dd40/src/main/java/de/erdbeerbaerlp/dcintegration/common/storage/Configuration.java#L508 )

How do you do this in 1.12?

**Comment by ErdbeerbaerLP** [comment]
> > You have to set the channel ID of command log.channelID in your config
> > (Variable in code:
> > https://github.com/ErdbeerbaerLP/DiscordIntegration-Core/blob/f8762f79a70b95c33032fce419e0e386edf3dd40/src/main/java/de/erdbeerbaerlp/dcintegration/common/storage/Configuration.java#L508 )
> 
> How do you do this in 1.12?

You can't yet

**Comment by ErdbeerbaerLP** [comment]
Latest 1.12 update should allow it now
