### ISSUE TITLE
[Suggestion] Make it possible to use this on multiple discord servers

### ISSUE THREAD

**Issue by Demmens** [ErdbeerbaerLP/DiscordIntegration-Forge#261]
**Platform**
-
- [x] Forge
- [ ] Spigot

**What you want to be added?**
- Allow the use of multiple discord text channels so I can have the minecraft server span multiple discord servers.

**Comment by ErdbeerbaerLP** [comment]
It is not planned to make it work on multiple servers at the same time, as some or more features will break doing this.
