### ISSUE TITLE
[BUG] When server stopping

### ISSUE THREAD

**Issue by SpeeeDCraft** [ErdbeerbaerLP/DiscordIntegration-Forge#264]
**What happened?**
Error when stopping the server

**What should happen?**
The server should have stopped

**Steps to reproduce**
- Install Forge Server 1.16.5
- Install DiscordIntegration
- Start server
- Stop server
- Error in console

**Version**
- 1.16.5

**Platform**
- [36.1.16] Forge

Mod version: 
- DiscordIntegration-Forge 2.1.1 (MC 1.16.5)

**Config file**
- https://pastebin.com/nXx13qxQ

**Crash report if available**
https://pastebin.com/gMkJudiB

**Additional info**
none

**Comment by ErdbeerbaerLP** [comment]
*reopen as it is not released yet*

**Comment by ErdbeerbaerLP** [comment]
https://www.curseforge.com/minecraft/mc-mods/dcintegration/files/3308615
