### ISSUE TITLE
[BUG] Bot wont go online and now mod crashes my server

### ISSUE THREAD

**Issue by leonx132** [ErdbeerbaerLP/DiscordIntegration-Forge#270]
**What happened?**
- Bot wont go online and now mod crashes my server

**Version**
- 1.16

**Platform**
-  Forge

Mod version: 

**Config file & Crash report**
[Config and crash report .zip](https://github.com/ErdbeerbaerLP/DiscordIntegration-Forge/files/6526513/Config.and.crash.report.zip)

**Comment by ErdbeerbaerLP** [comment]
Just looked at it and found the issue

Your line: `notWhitelisted = "§cYou are not whitelisted.\nJoin the discord server for more information\https://discord.gg/tgmvRMAfV7"`

Fixed config entry: `notWhitelisted = "§cYou are not whitelisted.\nJoin the discord server for more information\nhttps://discord.gg/tgmvRMAfV7"`

(you missed the 'n' of '\n')
