### ISSUE TITLE
No configuration file MC 1.12.2 Forge

### ISSUE THREAD

**Issue by axalox** [ErdbeerbaerLP/DiscordIntegration-Forge#274]
Hello

I've installed **DiscordIntegration-1.1.18 (MC 1.12)** on a 1.12.2 MC Forge server.
I try to follow the wiki for the installation but the mod didn't create config file.
I've looked in /mods, /config but i can't find it, is there a command to do in game for create this config file ?

**Comment by hoblin** [comment]
Same problem. There is the following message in the log
```
[14:21:57] [Server thread/INFO] [FML]: FML has found a non-mod file DiscordCraft-2.0.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
```

**Comment by ErdbeerbaerLP** [comment]
DiscordCraft is an [different mod](https://www.curseforge.com/minecraft/mc-mods/minecraft-rich-presence). Also it is client side... Get DiscordIntegration [HERE](https://www.curseforge.com/minecraft/mc-mods/dcintegration) if you actually wanted an discord <==> server chat bridge

**Comment by hoblin** [comment]
> HERE

Oh, thank you. That one have a link to this repo
