### ISSUE TITLE
[BUG] Error response upon server launch

### ISSUE THREAD

**Issue by MicTheObnoxious** [ErdbeerbaerLP/DiscordIntegration-Forge#276]
**What happened?**
- Error response upon server launch:

> [STDERR/]: [de.erdbeerbaerlp.dcintegration.common.Discord:getChannel:276]: Failed to get channel with ID '813775120010706984', falling back to default channel

Have attempted alternative servers, channels, etc. Same message persists

**What should happen?**
- Should connx. to channel and work?

**Steps to reproduce**
- N/A

**Version**

- [x] 1.16

**Platform**

- [x] Forge

Mod version: 

**Config file**
-
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://hastebin.com)**
-

**Additional info**
-

**Comment by weightmaker** [comment]
+1 i have the same issue. 
followed the quick guide step by step but the bot never comes online and getting the same error

my config file: https://pastebin.com/c2m8YiK8
Edited the bot-token but kept the special characters if it only needs a certain part of it and the guide doesnt say
