### ISSUE TITLE
[BUG] Errors, Delayed Messages or Errors while trying to send one.

### ISSUE THREAD

**Issue by ShadowWolf90** [ErdbeerbaerLP/DiscordIntegration-Forge#280]
**What happened?**
- Lots of errors occurs while starting while trying to connect to socket after 50 times and finally connects to bot.
- Delayed messages or 0 messages on chat.

**What should happen?**
-  No Errors and connect to bot in a few moments after loading a mods.

**Steps to reproduce**
- Start server on 1.12.2
- Console throws errors.

**Version**
-
- [X] 1.12
- [ ] 1.16

**Platform**
-
- [X] Forge
- [ ] Spigot

Mod version:  1.1.18

**Config file**
- https://pastebin.com/q4jyDq9m
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Additional info**
- https://pastebin.com/3hzBFAyZ - Error that occurs.

**Comment by ErdbeerbaerLP** [comment]
Try version 2.2.0 for 1.12, maybe the issue is solved there.

Also make sure you have enabled Server Members Intent
