### ISSUE TITLE
[Suggestion] Admin message the bot to get linked accounts

### ISSUE THREAD

**Issue by jpwanabe** [ErdbeerbaerLP/DiscordIntegration-Forge#287]
**Platform**
-
- [ ] Forge
- [ ] Spigot
Bot would be good
**What you want to be added?**
-
It would be awesome if as an admin with a set group that I could message the bot with something like "/check minecraft mcname" or "/check discord discordname" to get the linked accounts for that name. And a "/check all" to get the whole file printed to us. 

Now if this exists already, I can find nothing on the wiki or in the config file on how to do this already. If we can get that updated if this is the case that would be awesome.

**Comment by ErdbeerbaerLP** [comment]
Implemented in 2.3.0
(see /linkcheck)
