### ISSUE TITLE
[Suggestion] Add support for discord slash commands

### ISSUE THREAD

**Issue by HandyHat** [ErdbeerbaerLP/DiscordIntegration-Forge#298]
**Platform**
-
- [x] Forge
- [ ] Spigot

**What you want to be added?**
- [Discord slash command support](https://discord.com/developers/docs/interactions/slash-commands) for the custom commands so that the commands can appear next to all the other bot commands, and a custom prefix is not necessary
- It is supported by [JDA](https://github.com/DV8FromTheWorld/JDA/wiki/Interactions#slash-commands)

**Comment by ErdbeerbaerLP** [comment]
Implemented in 2.3.0
