### ISSUE TITLE
[Suggestion] Ability to check Discord Username of Player and vice versa

### ISSUE THREAD

**Issue by Roadcrosser** [ErdbeerbaerLP/DiscordIntegration-Forge#300]
**Platform**
-
- [x] Forge
- [ ] Spigot

**What you want to be added?**

I'm not sure if it's already a thing that I missed, but it would be nice if I could, preferably through bot command, check which player is which user, mostly for moderation/enforcement purposes.

**Comment by ErdbeerbaerLP** [comment]
Implemented in 2.3.0

/linkcheck
