### ISSUE TITLE
[Suggestion] Additional config options

### ISSUE THREAD

**Issue by Roadcrosser** [ErdbeerbaerLP/DiscordIntegration-Forge#301]
**Platform**
-
- [x] Forge
- [ ] Spigot

**What you want to be added?**

There are some config-related features I would like, namely disabling the feature that converts a player's name to their Discord nick.

Additionally (though I feel this suggestion would be better suited to DiscordIntegration-Core), is the ability to disable specific user-settings. For example, I would want to disable the ability for users to hide their ingame messages from Discord, so that we would be able to monitor chat without somebody slipping under the radar with this setting.

I did try to compile this on my own in order to prevent the "hideFromDiscord" check from happening, but ran into a wall with MCP issues.

**Comment by ErdbeerbaerLP** [comment]
> There are some config-related features I would like, namely disabling the feature that converts a player's name to their Discord nick.
This *should* work by changing an user setting (`"useDiscordNameInChannel": true`), if not simply re-open this

Everything else is now implemented now in 2.3.0
