### ISSUE TITLE
Discord Messages Not Being Sent To Minecraft [BUG] 

### ISSUE THREAD

**Issue by technodragon253** [ErdbeerbaerLP/DiscordIntegration-Forge#306]
**What happened?**
-After following the quick start guide I was able to get the bot to work and messages from minecraft showed up perfectly in discord, but messages from discord didn't show in the minecraft chat. 

**What should happen?**
-Messages in discord should be sent into the minecraft chat.

**Steps to reproduce**
- Using forge 36.2.0 make a server following the quick start guide.
- Link to discord.
[Discord-Integration.txt](https://github.com/ErdbeerbaerLP/DiscordIntegration-Forge/files/6911244/Discord-Integration.txt)

**Version**
-
- [ ] 1.12
- [x] 1.16

**Platform**
-
- [x] Forge
- [ ] Spigot

Mod version: 2.1.1

**Config file**
-I attached it as a .txt file in the server it is a .toml file 
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://hastebin.com)**
-

**Additional info**
-

**Comment by ErdbeerbaerLP** [comment]
Update the mod and tell me if this issue perists

**Comment by technodragon253** [comment]
Okay I will try that, thanks!

**Comment by technodragon253** [comment]
Updated to 2.3.1 and it worked perfectly. Thank you for your help!
