### ISSUE TITLE
[BUG] Crash on start up using newist version

### ISSUE THREAD

**Issue by jpwanabe** [ErdbeerbaerLP/DiscordIntegration-Forge#308]
**What happened?**
- Crash on boot
- 
**What should happen?**
- no crash

**Steps to reproduce**
- 
- Start server

**Version**
-
- [ ] 1.12
- [X ] 1.16

**Platform**
-
- [X ] Forge
- [ ] Spigot

Mod version: 
dcintegration-forge-2.3.2-1.16
**Config file**
-https://pastebin.com/i3MBd4RX
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://hastebin.com)**
-https://pastebin.com/JKLi1rYi

**Additional info**
-

**Comment by ErdbeerbaerLP** [comment]
Did you re-invite the bot giving it slash command permisions?
Just repeat step 2 again without kicking your bot: https://github.com/ErdbeerbaerLP/DiscordIntegration-Forge/wiki/Quick-Setup#2-add-the-bot-to-your-discord-server

**Comment by jpwanabe** [comment]
It worked. I did that wrong the first time it seems. Your link solved it.
