### ISSUE TITLE
[BUG] Can not whitelist the same way as last versions.

### ISSUE THREAD

**Issue by jpwanabe** [ErdbeerbaerLP/DiscordIntegration-Forge#309]
**What happened?**
-Users can not whitelist in the same way last versions did.

**What should happen?**
-Users should be able to whitelist them selves by messaging the bot /whitelist "name"

**Steps to reproduce**
- Message the bot with /whitelist "name" and it does not respond. Joining the server gives an error that you are not whitelisted.
- 

**Version**
-
- [ ] 1.12
- [ X] 1.16

**Platform**
-
- [X] Forge
- [ ] Spigot

Mod version: 
dcintegration-forge-2.3.2-1.16.jar
**Config file**
-https://pastebin.com/i3MBd4RX
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://hastebin.com)**
-

**Additional info**
-If there is a newer command to do the whitelist, I can't figure it out or find any documentation on it.

**Comment by ErdbeerbaerLP** [comment]
To whitelist now, uers have to join the server once to get an code in the kick message, then use !link <whitelist-code>

**Comment by jpwanabe** [comment]
Do they use it in a PM to the bot or in the channel im using for the chat?

**Comment by ErdbeerbaerLP** [comment]
In the DMs of the bot

**Comment by jpwanabe** [comment]
Alright. Thank you. I would add that to the wiki though. There was no documentation about the change so I was not aware.
