### ISSUE TITLE
Error spam in console

### ISSUE THREAD

**Issue by aut1sto** [ErdbeerbaerLP/DiscordIntegration-Forge#314]
Error spam in console, not causes crash.
Version: 1.12.2
Platform: Forge
Forge version: 14.23.5.2855
Mod version:  1.1.18
Error: https://hastebin.com/ojicapolid
Log: [2021-08-09-4.log](https://github.com/ErdbeerbaerLP/DiscordIntegration-Forge/files/6954980/2021-08-09-4.log)
Config: [Discord-Integration.zip](https://github.com/ErdbeerbaerLP/DiscordIntegration-Forge/files/6954995/Discord-Integration.zip)

**Comment by ErdbeerbaerLP** [comment]
Update the mod to see if it is still an issue

**Comment by aut1sto** [comment]
its fixed now, thx
