### ISSUE TITLE
[Bug]: Crash on newest 1.16.5 version

### ISSUE THREAD

**Issue by jpwanabe** [ErdbeerbaerLP/DiscordIntegration-Forge#358]
### What happened?

Crash report as follows.
Also the file is super small compared to old versions
I do believe this is the wrong version based on the file it downloaded
https://www.curseforge.com/minecraft/mc-mods/dcintegration/files/3508342
downloads 
dcintegration-forge-2.3.5-1.17

### Game Version

1.16

### What platform are you using?

Forge

### Platform version

dcintegration-forge-2.3.5-1.17

### Config File

```toml
New install no config yet
```

### Crash report / Error log (if applicable)

```shell
https://pastebin.com/eVgCSHe5
```

**Comment by Dovahkiin-Warrior** [comment]
```
-- MOD dcintegration --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/dv8tion/jda/api/entities/MessageChannel
```

Same.

**Comment by Novtalath** [comment]
Seems a broken download link. Downloads mod for MC1.17 and not for MC1.16 I had to regress to one version down.

**Comment by jpwanabe** [comment]
I really want this version to work. I'm hoping it will stop the issue of people messaging the bot weird things and it crashing and causing ram to spike

**Comment by Andiq** [comment]
I think i found the issue i had nearly the same error then i refreshed the bot token and now it seems to work before my bot token had 3 "." in it and now it has none idk if that is the fix but it did it for me lol.

**Comment by ErdbeerbaerLP** [comment]
Well... that is fixed now, it was uploaded wrongly multiple times for some reason
