### ISSUE TITLE
[Suggestion]: Add TPS command to return /forge tps stats

### ISSUE THREAD

**Issue by mikeace420** [ErdbeerbaerLP/DiscordIntegration-Forge#365]
### Explain your idea

I would like to see a TPS command implemented so you can see the forge server TPS stats from within Discord.

### If this is platform-dependant, which platform is this about?

Forge

**Comment by ErdbeerbaerLP** [comment]
You can create that command on [this website](https://erdbeerbaerlp.de/dcintegration-commands/) and put it in your config file.
Will not add it to default config as /forge tps is an platform-dependant command
