### ISSUE TITLE
[Bug]: Mod cannot be used on 1.18.1

### ISSUE THREAD

**Issue by Sunconure11** [ErdbeerbaerLP/DiscordIntegration-Forge#374]
### What happened?

A bug happened!

### Game Version

Other

### What platform are you using?

Forge

### Platform version

2.3.5 Forge

### Config File

```toml
Not applicable, due to the nature of this issue
```

### Crash report / Error log (if applicable)

```shell
Not applicable
```

### Additional Information

The mod appears to be unable to run on 1.18.1, thus causing any server to crash when attempting to boot up, should they be using that version of Forge.

**Comment by mmmmmmmmmmmmmmmmaly** [comment]
same here

**Comment by Sunconure11** [comment]
This appears to have been resolved.
