### ISSUE TITLE
[Bug]: (1.18.2) Cannot use "SAY" command from the server console

### ISSUE THREAD

**Issue by belathus** [ErdbeerbaerLP/DiscordIntegration-Forge#448]
### What happened?

A bug happened!

### Game Version

Other

### What platform are you using?

Forge

### Platform version

40.1.20

### Config File

```toml
Default config
```

### Crash report / Error log (if applicable)

```shell
https://gist.github.com/belathus/9bb988944f188f707371d8d6ffcdad56
```

### Additional Information

Pulling the mod resolved the issue.

**Comment by ErdbeerbaerLP** [comment]
Should be fixed in alpha 2.4.3

(Currently slowly sifting through all issues)
